// <auto-generated />
namespace REPLSolutions.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddAcademicCalanderEventToAcademicCalanderModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAcademicCalanderEventToAcademicCalanderModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202102140952004_AddAcademicCalanderEventToAcademicCalanderModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
